apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: k8s-deployment-pipeline
build:
  artifacts:
  - image: myapp
    context: app
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl: {}
portForward:
- resourceType: service
  resourceName: dev-myapp
  namespace: dev
  port: 8080
  localPort: 8080
