apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yml

commonLabels:
  environment: staging

namePrefix: staging-

images:
- name: myapp
  newTag: staging